name: Docker Image Build And Deploy

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: self-hosted 
    steps:
      - name: Checking Docker Installation
        run: |
          docker version
          
      - name: Checkout repository
        uses: actions/checkout@v4 
        
